services:
  seplag-api:
    image: seplag-api:0.0.1-SNAPSHOT
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/seplag
    container_name: seplag-api
    hostname: seplag-api
    depends_on:
      - postgres_db
    networks:
      - seplag-network
    
include:
  - ./postgres/compose.yml
  
networks:
  seplag-network:
    driver: bridge
