services:
  seplag-api:
    build: .
    image: seplag-api:0.0.1-SNAPSHOT
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/seplag
      - MINIO_ENDPOINT=http://minio:9000
    container_name: seplag-api
    hostname: seplag-api
    networks:
      - seplag-network
    depends_on:
      - postgres_db
      - minio
      
  postgres_db:
    image: postgres:17.4
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: seplag#2025
      POSTGRES_USER: postgres
      POSTGRES_DB: seplag
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - seplag-network
    
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"     # API port
      - "9001:9001"     # Console port
    volumes:
      - minio_data:/var/lib/minio/data
    environment:
      MINIO_ROOT_USER: minioadmin     # Usuário de acesso
      MINIO_ROOT_PASSWORD: minioadmin # Senha de acesso
      MINIO_CONSOLE_ADDRESS: ":9001"  # Endereço de bind do console
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - seplag-network
      
volumes:
  postgres_data:
  minio_data:
  
networks:
  seplag-network:
    driver: bridge
