INSERT INTO cidade (cid_nome, cid_uf) VALUES
('Cuiabá', 'MT'),
('Várzea Grande', 'MT'),
('Rondonópolis', 'MT'),
('Sinop', 'MT'),
('Tangará da Serra', 'MT'),
('Cáceres', 'MT'),
('Sorriso', 'MT'),
('Lucas do Rio Verde', 'MT'),
('Primavera do Leste', 'MT'),
('Barra do Garças', 'MT'),
('Alta Floresta', 'MT'),
('Pontes e Lacerda', 'MT'),
('Campo Verde', 'MT'),
('Nova Mutum', 'MT'),
('Juína', 'MT'),
('Colíder', 'MT'),
('Guarantã do Norte', 'MT'),
('Juara', 'MT'),
('Poconé', 'MT'),
('Diamantino', 'MT');