services:
  postgres_db:
    image: postgres:17.4
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: seplag#2025
      POSTGRES_USER: postgres
      POSTGRES_DB: seplag
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - /.docker/seplag/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8081
    depends_on:
      - postgres_db
 
volumes:
  pgdata: