services:
  postgres_db:
    image: postgres:17.4
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: seplag#2025
      POSTGRES_USER: postgres
      POSTGRES_DB: seplag
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local