services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: seplag#2025
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 5432:5432
 
volumes:
  pgdata: